[workspace]
channels = ["conda-forge", "https://prefix.dev/sofa-framework"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[dependencies]
python = ">=3.9,<3.15"
attrs = ">=22.1.0,<26"
pandas = ">=2.1.1,<4"
ruff = ">=0.12.7,<0.16"

[pypi-dependencies]
sim-labs = { path = ".", editable = true }

[tasks]
ruff-check = "ruff check"
ruff-fix = "ruff check --fix"

[feature.DEMO_APP.dependencies]
matplotlib = ">=3.9.4,<4"
pygame = ">=2.6.1,<3"
pymunk = ">=7.0.1,<8"
xlsxwriter = ">=3.2.3,<4"
openpyxl = ">=3.1.5,<4"

[feature.DEMO_APP.tasks]
DEMO_APP = "python ./src/nuremics_labs/apps/general/DEMO_APP/system.py"

[feature.CANTILEVER_SHEAR_APP.dependencies]
pythonocc-core = ">=7.4.0,<8"
openpyxl = ">=3.1.5,<4"
matplotlib = ">=3.9.4,<4"
sofa-app = "=25.6.0"
sofa-python3 = "=25.6.0"

[feature.CANTILEVER_SHEAR_APP.pypi-dependencies]
gmsh = ">=4.15.0,<5"
meshio = ">=5.3.5,<6"
numpy = ">=2.4.2,<3"
pyvista = ">=0.47.1,<0.48"

[feature.CANTILEVER_SHEAR_APP.tasks]
CANTILEVER_SHEAR_APP = "python ./src/nuremics_labs/apps/simulation/CANTILEVER_SHEAR_APP/system.py"
GeometryProc = "python ./src/nuremics_labs/apps/simulation/CANTILEVER_SHEAR_APP/procs/GeometryProc/item.py"
LabelingProc = "python ./src/nuremics_labs/apps/simulation/CANTILEVER_SHEAR_APP/procs/LabelingProc/item.py"
MeshProc = "python ./src/nuremics_labs/apps/simulation/CANTILEVER_SHEAR_APP/procs/MeshProc/item.py"
ModelProc = "python ./src/nuremics_labs/apps/simulation/CANTILEVER_SHEAR_APP/procs/ModelProc/item.py"
SolverProc = "python ./src/nuremics_labs/apps/simulation/CANTILEVER_SHEAR_APP/procs/SolverProc/item.py"
PostProc = "python ./src/nuremics_labs/apps/simulation/CANTILEVER_SHEAR_APP/procs/PostProc/item.py"
AnalysisProc = "python ./src/nuremics_labs/apps/simulation/CANTILEVER_SHEAR_APP/procs/AnalysisProc/item.py"

[environments]
demo = ["DEMO_APP"]
cantilever-shear = ["CANTILEVER_SHEAR_APP"]
