workflow:
  - process: nuremics_labs.procs.general.PolygonGeometryProc
    user_params:
      n_sides: nb_sides
    hard_params:
      radius: 0.5
    user_paths:
      title_file: plot_title.txt
    output_paths:
      coords_file: points_coordinates.csv
      fig_file: polygon_shape.png

  - process: nuremics_labs.procs.general.ProjectileModelProc
    user_params:
      gravity: gravity
      mass: mass
    user_paths:
      velocity_file: velocity.json
      configs_folder: configs
    required_paths:
      coords_file: points_coordinates.csv
    output_paths:
      comp_folder: comparison

  - process: nuremics_labs.procs.general.TrajectoryAnalysisProc
    overall_analysis:
      comp_folder: comparison
    output_paths:
      fig_file: overall_comparisons.png
    settings:
      add: true
      color: red
      linestyle: None
      linewidth: 2.0
      marker: o
      markersize: 8
      markevery: 20
      label: ""

default_params:
  "nb_sides": 5
  "gravity": -9.81
  "mass": 0.1